# Generated by Django 5.1.3 on 2024-12-14 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_book_alter_loginstreak_consecutive_days_bookissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 1, 11)),
        ),
    ]
