# Generated by Django 5.1.3 on 2024-12-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_bookissue_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='due_date',
            field=models.DateField(),
        ),
    ]
