# Generated by Django 5.1.3 on 2024-12-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_bookissue_check_due_date_after_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
