# Generated by Django 5.1.3 on 2024-12-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_bookissue_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='return_date',
        ),
    ]
