# Generated by Django 5.1.3 on 2024-12-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_bookissue_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='due_date',
            field=models.DateField(),
        ),
    ]
